### ISSUE TITLE
Typo in line 42

### ISSUE THREAD

**Issue by skippernl** [T13nn3s/Windows10BuildUpdater#1]
Line 42 reads New-Item -path "C:\PowershellWindows10BuildUpdater" -Name "PSWindowsUpate.log" -Force -Erroraction SilentlyContinue
There is a typo file name should be PSWindowsUpdate.log You could also remove the line as the correct log file is also created.

**Comment by T13nn3s** [comment]
Thanks mate! Just updates the script.
